FROM debian:buster@sha256:2857989334428416b1ef369d6e029e912a7fe3ee7e57adc20b494cc940198258
COPY buster_deps.sh /deps.sh
RUN /deps.sh && rm /deps.sh
VOLUME /wallycore
ENV JAVA_HOME=/usr/lib/jvm/java-1.11.0-openjdk-amd64
ENV ANDROID_NDK=/opt/android-ndk-r20
