#
# Dockerfile for wally builds.
# build from this directory with e.g:
#     DOCKER_BUILDKIT=1 docker build . -t greenaddress/wallycore -f Dockerfile_bullseye
#
FROM debian:bullseye@sha256:71cb300d5448af821aedfe63afd55ba05f45a6a79f00dcd131b96b780bb99fe4
WORKDIR /root
COPY bullseye_deps.sh ./deps.sh
COPY requirements.txt ./contrib/requirements.txt
RUN ./deps.sh && rm ./deps.sh
ENV JAVA_HOME=/usr/lib/jvm/java-1.11.0-openjdk-amd64
ENV ANDROID_NDK=/opt/android-ndk-r26b
