#!/usr/bin/env python
"""
Differential test harness: libwally miniscript satisfier vs rust-miniscript golden witnesses.

Corpus is loaded from the same miniscript_vectors.json used by test_bip379_vectors.py.
Golden witnesses are generated by a rust-miniscript reference implementation and stored
in data/bip379/satisfier_golden.json (generated by gen_golden in src/data/bip379/gen_golden/).
"""
import hashlib
import json
import os
import re
import unittest
from ctypes import *
from util import *

NETWORK_NONE = 0x00
MS_ONLY = 0x2   # WALLY_MINISCRIPT_ONLY
EC_PUBLIC_KEY_LEN = 33
FLAG_GRIND_R = 0x4

# Key secrets: sk[0] = i, sk[1..31] = 0x00
_SK_SECRETS = [bytes([i]) + b'\x00' * 31 for i in range(1, 21)]

# Preimage bytes and their hashes (SHA256 / RIPEMD160):
#   _SHA256_PRE = [0x12;32]  ->  SHA256([0x12;32])
#   _RIPEMD_PRE = [0x78;32]  ->  RIPEMD160([0x78;32])
_SHA256_PRE = bytes([0x12] * 32)
_RIPEMD_PRE = bytes([0x78] * 32)
_SHA256_H   = 'b6acca81a0939a856c35e4c4188e95b91731aab1d4629a4cee79dd09ded4fc94'
_RIPEMD_H   = '6646adac9fb158a6df66130746d48a0e7f9db390'

_DATA_DIR    = os.path.join(os.path.dirname(__file__), '..', 'data', 'bip379')
_GOLDEN_PATH = os.path.join(_DATA_DIR, 'satisfier_golden.json')


def _derive_pubkey(sk_bytes):
    pub, pub_len = make_cbuffer('00' * EC_PUBLIC_KEY_LEN)
    ret = wally_ec_public_key_from_private_key(sk_bytes, len(sk_bytes), pub, pub_len)
    assert ret == WALLY_OK, '_derive_pubkey failed'
    return bytes(pub)


_PK_LIST = [_derive_pubkey(sk) for sk in _SK_SECRETS]
# pubkey_hex -> secret_key_bytes — used during signing phase
_PK_MAP = {pk.hex(): sk for sk, pk in zip(_SK_SECRETS, _PK_LIST)}


def _sub_h(ms):
    """Replace H placeholders with concrete hash hex values."""
    ms = ms.replace('hash256(H)', 'hash256(' + _SHA256_H + ')')
    ms = ms.replace('sha256(H)',  'sha256('  + _SHA256_H + ')')
    ms = ms.replace('hash160(H)', 'hash160(' + _RIPEMD_H + ')')
    ms = ms.replace('ripemd160(H)', 'ripemd160(' + _RIPEMD_H + ')')
    return ms


def _load_corpus():
    """Load valid miniscript cases from miniscript_vectors.json."""
    with open(os.path.join(_DATA_DIR, 'miniscript_vectors.json'), 'r') as f:
        data = json.load(f)
    return [(_sub_h(tc['miniscript']), tc.get('comment', '')) for tc in data['valid_cases']]


def _load_golden():
    """Load golden witness data if available."""
    if os.path.exists(_GOLDEN_PATH):
        with open(_GOLDEN_PATH, 'r') as f:
            return json.load(f)
    return {}


_PUBKEY_RE = re.compile(r'\b(0[23][0-9a-f]{64})\b')


def _extract_pubkeys(ms_str):
    """Return unique compressed pubkeys (hex→bytes) found in a miniscript string."""
    seen = {}
    for m in _PUBKEY_RE.finditer(ms_str):
        h = m.group(1)
        if h not in seen:
            seen[h] = bytes.fromhex(h)
    return list(seen.values())


def build_p2wsh_psbt(script_bytes, extra_pubkeys=(), amount=200000):
    """Build a minimal P2WSH PSBT for the given witness script with hash preimages set."""
    # P2WSH scriptpubkey: OP_0 <sha256(script)>
    script_hash = hashlib.sha256(script_bytes).digest()
    p2wsh_spk = bytes([0x00, 0x20]) + script_hash

    # Create the P2WSH output
    spk_buf, spk_len = make_cbuffer(p2wsh_spk.hex())
    output = pointer(wally_tx_output())
    assert wally_tx_output_init_alloc(amount, spk_buf, spk_len, output) == WALLY_OK

    # Create funding tx: version 2, 1 dummy input, 1 P2WSH output
    tx = pointer(wally_tx())
    assert wally_tx_init_alloc(2, 0, 1, 1, tx) == WALLY_OK

    txid_buf, txid_len = make_cbuffer('ab' * 32)
    assert wally_tx_add_raw_input(tx, txid_buf, txid_len, 0, 0xFFFFFFFE,
                                  None, 0, None, 0) == WALLY_OK
    assert wally_tx_add_output(tx, output) == WALLY_OK

    # Create PSBT v0 and attach the global tx.  Pass 0 pre-allocated inputs so
    # psbt_set_global_tx allocates them via psbt_input_init, which properly sets
    # up the keypaths map's verify_fn (needed by wally_psbt_add_input_keypath).
    psbt = pointer(wally_psbt())
    assert wally_psbt_init_alloc(0, 0, 0, 0, 0, psbt) == WALLY_OK
    assert wally_psbt_set_global_tx(psbt, tx) == WALLY_OK

    # Annotate input 0 with witness_utxo and witness_script
    assert wally_psbt_set_input_witness_utxo(psbt, 0, output) == WALLY_OK
    script_buf, script_len = make_cbuffer(script_bytes.hex())
    assert wally_psbt_set_input_witness_script(psbt, 0, script_buf, script_len) == WALLY_OK

    # Add hash preimages directly into input 0's preimage map via ctypes pointer arithmetic.
    # There is no high-level API for this, so we compute the field address ourselves.
    inputs_raw = cast(psbt.contents.inputs, c_void_p).value
    preimage_offset = wally_psbt_input.preimages.offset
    preimage_map_ptr = cast(inputs_raw + preimage_offset, POINTER(wally_map))

    pre_sha, pre_sha_len = make_cbuffer(_SHA256_PRE.hex())
    assert wally_map_preimage_sha256_add(preimage_map_ptr, pre_sha, pre_sha_len) == WALLY_OK

    pre_rmd, pre_rmd_len = make_cbuffer(_RIPEMD_PRE.hex())
    assert wally_map_preimage_ripemd160_add(preimage_map_ptr, pre_rmd, pre_rmd_len) == WALLY_OK

    # Register all known pubkeys as keypaths so p2wsh_lookup_pkh can resolve pk_h fragments
    # and wally_psbt_sign can add signatures for them.
    fingerprint, fingerprint_len = make_cbuffer('00' * 4)
    seen_pks = set()
    for pk in list(_PK_LIST) + list(extra_pubkeys):
        if pk in seen_pks:
            continue
        seen_pks.add(pk)
        pk_buf, pk_len = make_cbuffer(pk.hex())
        assert wally_psbt_add_input_keypath(psbt, 0, pk_buf, pk_len,
                                            fingerprint, fingerprint_len,
                                            None, 0) == WALLY_OK

    return psbt, 0


def finalize_and_extract_witness(psbt, input_idx=0):
    """Sign (best-effort), finalize, and return the final witness item list as hex strings."""
    for sk in _SK_SECRETS:
        sk_buf, sk_len = make_cbuffer(sk.hex())
        wally_psbt_sign(psbt, sk_buf, sk_len, FLAG_GRIND_R)

    if wally_psbt_finalize(psbt, 0) != WALLY_OK:
        return None

    final_witness_ptr = psbt.contents.inputs[input_idx].final_witness
    if not final_witness_ptr:
        return None

    stack = final_witness_ptr.contents
    items = []
    for i in range(stack.num_items):
        item = stack.items[i]
        if item.len == 0 or not item.witness:
            items.append('')
        else:
            items.append(string_at(item.witness, item.len).hex())
    return items


class MiniscriptSatisfierDiffTests(unittest.TestCase):
    """Differential: libwally satisfier vs rust-miniscript golden witnesses."""

    @classmethod
    def setUpClass(cls):
        cls.corpus = _load_corpus()
        cls.golden = _load_golden()

    def test_segwit_v0_witnesses_match_golden(self):
        """Each corpus item: finalize as p2wsh, compare witness with rust-miniscript golden."""
        for ms_str, comment in self.corpus:
            if ms_str not in self.golden:
                continue

            d = c_void_p()
            ret = wally_descriptor_parse(ms_str, None, NETWORK_NONE, MS_ONLY, d)
            if ret != WALLY_OK:
                continue
            script, script_len = make_cbuffer('00' * 10000)
            ret, written = wally_descriptor_to_script(d, 0, 0, 0, 0, 0, 0, script, script_len)
            wally_descriptor_free(d)
            if ret != WALLY_OK:
                continue

            script_bytes = bytes(script[:written])
            extra_pks = _extract_pubkeys(ms_str)
            psbt, input_idx = build_p2wsh_psbt(script_bytes, extra_pubkeys=extra_pks)
            witness = finalize_and_extract_witness(psbt, input_idx)
            wally_psbt_free(psbt)

            expected = self.golden[ms_str]
            self.assertIsNotNone(
                witness,
                f'[{comment}] finalization failed for: {ms_str!r}',
            )
            self.assertEqual(
                witness, expected,
                f'[{comment}] witness mismatch for: {ms_str!r}',
            )

    def test_tapscript_witnesses_match_golden(self):
        """Each corpus item wrapped in tr(): finalize tapscript path, compare witness."""
        # No tapscript golden data generated yet — all golden entries are segwit v0.
        # This test passes trivially; extend golden with tapscript entries to add coverage.
        for ms_str, _comment in self.corpus:
            tap_key = f'tap:{ms_str}'
            if tap_key not in self.golden:
                continue
            # Tapscript comparison would go here once golden has tap: entries.

    def test_j_wrapper_dissatisfaction_regression(self):
        """Regression for the j: (NON_ZERO) dissatisfaction fix.

        A j:-wrapped fragment in a dissatisfiable position (here, the left arm of
        or_d) must be dissatisfiable with a single empty push, so the other branch
        can still be spent. The j: branch's timelocks are unsatisfiable here (the
        spending input disables relative locktime and nLockTime is 0), so the
        satisfier must dissatisfy it and sign the pk() branch. Previously j:
        dissatisfaction was IMPOSSIBLE, which made this script unspendable
        (finalization returned no witness)."""
        pk = _PK_LIST[1].hex()  # a key the harness can sign with (sk = 0x02..)
        ms = 'or_d(j:and_v(vdv:after(1567547623),older(16)),pk(%s))' % pk

        d = c_void_p()
        self.assertEqual(WALLY_OK,
                         wally_descriptor_parse(ms, None, NETWORK_NONE, MS_ONLY, d),
                         'failed to parse j: regression miniscript')
        script, script_len = make_cbuffer('00' * 10000)
        ret, written = wally_descriptor_to_script(d, 0, 0, 0, 0, 0, 0, script, script_len)
        wally_descriptor_free(d)
        self.assertEqual(WALLY_OK, ret, 'failed to compile j: regression miniscript')
        script_bytes = bytes(script[:written])

        psbt, idx = build_p2wsh_psbt(script_bytes, extra_pubkeys=[_PK_LIST[1]])
        witness = finalize_and_extract_witness(psbt, idx)
        wally_psbt_free(psbt)

        self.assertIsNotNone(
            witness,
            'or_d(j:...,pk) must finalize: the j: branch must be dissatisfiable '
            'so the pk() branch can be spent')
        # Witness ends with the witness script; a signature (DER, >=64 raw bytes,
        # i.e. >=128 hex chars) must be present for the spent pk() branch.
        self.assertEqual(witness[-1], script_bytes.hex())
        self.assertTrue(any(len(w) >= 128 for w in witness),
                        'expected a signature in the finalized witness, got %r' % witness)


if __name__ == '__main__':
    unittest.main()
