// Dart FFI binding to libwally-core
import 'dart:ffi';
import 'package:ffi/ffi.dart';
import 'dart:typed_data';

class NativeLibrary {
  /// Holds the symbol lookup function.
  final Pointer<T> Function<T extends NativeType>(String sym) _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  NativeLibrary(DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  NativeLibrary.fromLookup(
      Pointer<T> Function<T extends NativeType>(String sym) lookup)
      : _lookup = lookup;

// BEGIN AUTOGENERATED
// END AUTOGENERATED

  String base58_from_bytes(Uint8List bytes, int flags) {
      final arena = Arena();
      final output = arena<Pointer<Utf8>>();
      final bytes_len = bytes.length;
      final c_bytes = arena<Uint8>(bytes_len);
      c_bytes.asTypedList(bytes_len).setAll(0, bytes);
      final code = _wally_base58_from_bytes(c_bytes, bytes_len, flags, output);
      final String ret = output.value.cast<Utf8>().toDartString();
      _wally_free_string(output.value);
      return ret;
  }
} // class NativeLibrary

// BEGIN AUTOGENERATED TYPEDEFS
// END AUTOGENERATED TYPEDEFS

class words extends Opaque {}
class ext_key extends Opaque {}
class wally_map extends Opaque {}
class wally_psbt extends Opaque {}
class wally_psbt_input extends Opaque {}
class wally_psbt_output extends Opaque {}
class wally_tx extends Opaque {}
class wally_tx_input extends Opaque {}
class wally_tx_output extends Opaque {}
class wally_tx_witness_stack extends Opaque {}
class wally_operations extends Opaque {}
