#!/bin/bash
set -xeo pipefail

# Update function list in wasm_exports.sh and run codegen for the public API in functions.js
(cd ../.. && ./tools/build_wrappers.py)


# Build WASM (Elements is always enabled)
(cd ../.. && ./tools/build_wasm.sh --enable-elements)
mkdir -p libwally_wasm && cp ../../wally_dist/wallycore.{js,wasm} libwally_wasm/
# Rename to force commonjs mode. See https://github.com/emscripten-core/emscripten/pull/17451
mv libwally_wasm/wallycore.js libwally_wasm/wallycore.cjs


# Extract WALLY_ constants into const.js
: ${WALLY_INCLUDE_DIR:=../../include}
(echo '// AUTOGENERATED by build.sh' \
  && egrep -r '#define .* ' "$WALLY_INCLUDE_DIR" \
     | grep -v '#define OP_' \
     | sed -r 's~.*#define ([^ ]*) *~export const \1 = ~; s~( /\*)| *$~;\1~' \
     | sort \
) > const.js


# Update version number to match libwally's
current_version=$(grep -oP 'AC_INIT\(\[libwallycore\],\[\K[^\]]+' ../../configure.ac)
npm version --no-git-tag-version --allow-same-version "$current_version"
