#!/bin/bash

include_dir=${1:?"Usage: $0 <path-to-libwally-include-dir>"}

echo '// AUTOGENERATED by `npm run update-consts`'

egrep -r '#define .* ' $include_dir \
    | grep -v '#define OP_' \
    | sed -r 's~.*#define ([^ ]*) *~export const \1 = ~; s~( /\*)| *$~;\1~'
