#!/usr/bin/env python3
import os
import subprocess
import sys

# Structs with no definition in the public header files
OPAQUE_STRUCTS = [u'words']


def replace_text(filename, text, delims):
    lines = [line.rstrip() for line in open(filename)]
    start, end = lines.index(delims[0]), lines.index(delims[1])
    replaced = lines[:start + 1] + text + lines[end:]
    replaced = [l + u'\n' for l in replaced]
    open(filename, u'w').writelines([l for l in replaced])


def get_non_elements_functions():
    cmd = "-E include/*.h | sort | uniq | grep '^ *int ' | grep '(' | sed -e 's/^ *int //g' -e 's/(.*//g' | egrep '^wally_|^bip'"
    try:
        funcs = subprocess.check_output(u'gcc ' + cmd, shell=True)
    except subprocess.CalledProcessError:
        funcs = subprocess.check_output(u'clang ' + cmd, shell=True)
    return funcs.decode('utf-8').split(u'\n')


class Arg(object):
    def __init__(self, definition):
        if u'*' in definition:
            self.is_pointer = True
            self.is_pointer_pointer = u'**' in definition
            if self.is_pointer_pointer:
                self.type = definition.split(' **')[0] + '**'
            else:
                self.type = definition.split(' *')[0] + '*'
            self.name = definition[len(self.type) + 1:]
            self.is_struct = u'struct' in self.type
            if self.is_struct:
                self.struct_name = self.type.split(u' ')[-1].split(u'*')[0]
                self.is_opaque = self.struct_name in OPAQUE_STRUCTS
        else:
            self.is_pointer = False
            self.is_pointer_pointer = False
            self.is_struct = False
            self.type, self.name = definition.split(' ')
        self.is_const = self.type.startswith(u'const ')


class Func(object):
    def __init__(self, definition, non_elements):
        # Strip return type and closing ')', extract name
        self.name, definition = definition[4:-1].split(u'(')
        # Parse arguments
        self.args = [Arg(d) for d in definition.split(u', ')]
        self.is_elements = self.name not in non_elements

    def __lt__(self, other):
        return self.name < other.name


def is_array(func, arg, n, num_args, types):
    return arg.type in types and n != num_args -1 and \
               func.args[n + 1].type == u'size_t' and \
               func.args[n + 1].name.endswith(u'len')


def is_buffer(func, arg, n, num_args):
    return is_array(func, arg, n, num_args, [u'const unsigned char*', u'unsigned char*'])


def is_int_buffer(func, arg, n, num_args):
    return is_array(func, arg, n, num_args, [u'const uint32_t*', u'const uint64_t*'])


def gen_python_cffi(funcs, internal_only):
    typemap = {
        u'int'           : u'c_int',
        u'size_t*'       : u'c_size_t_p',
        u'size_t'        : u'c_size_t',
        u'uint32_t*'     : u'c_uint_p',
        u'uint32_t'      : u'c_uint32',
        u'uint64_t*'     : u'c_uint64_p',
        u'uint64_t'      : u'c_uint64',
        u'void**'        : u'POINTER(c_void_p)',
        u'void*'         : u'c_void_p',
        u'unsigned char*': u'c_void_p',
        u'char**'        : u'c_char_p_p',
        u'char*'         : u'c_char_p',
        u'wally_map_verify_fn_t' : u'c_void_p',
        }
    def map_arg(arg, n, num_args):
        argtype = arg.type[6:] if arg.is_const else arg.type # Strip const
        if argtype == u'uint64_t*' and n != num_args - 1:
            return u'POINTER(c_uint64)'
        if argtype in typemap:
            return typemap[argtype]
        if arg.is_struct:
            if arg.is_opaque:
                return typemap[u'void**' if arg.is_pointer_pointer else u'void*']
            text = f'POINTER({arg.struct_name})'
            if arg.is_pointer_pointer:
                text = f'POINTER({text})'
            return text
        assert False, f'ERROR: Unknown argument type "{argtype}"'

    cffi = []
    for func in funcs:
        num_args = len(func.args)
        mapped = u', '.join([map_arg(arg, i, num_args) for i, arg in enumerate(func.args)])
        cffi.append(f"    ('{func.name}', c_int, [{mapped}]),")

    cffi.sort()
    if internal_only:
        markers = [u'    # BEGIN INTERNAL AUTOGENERATED', u'    # END INTERNAL AUTOGENERATED']
    else:
        markers = [u'    # BEGIN AUTOGENERATED', u'    # END AUTOGENERATED']
    replace_text(u'src/test/util.py', cffi, markers)


def gen_python_swig(funcs):
    def map_arg(func, arg, n, num_args):
        if is_buffer(func, arg, n, num_args):
            macro = u'output' if arg.type == u'unsigned char*' else u'nullable'
            return f'%pybuffer_{macro}_binary({arg.type} {arg.name}, size_t {func.args[n + 1].name});'
        return u''

    swig = []
    for func in funcs:
        num_args = len(func.args)
        mapped = [map_arg(func, arg, i, num_args) for i, arg in enumerate(func.args)]
        swig.extend([m for m in mapped if m])

    swig = sorted(set(swig))
    replace_text(u'src/swig_python/swig.i', swig,
                 [u'/* BEGIN AUTOGENERATED */', u'/* END AUTOGENERATED */'])


def gen_java_swig(funcs):
    def map_arg(func, arg, n, num_args):
        if arg.type in [u'const unsigned char*', u'unsigned char*'] and \
                n != num_args -1 and func.args[n + 1].type == u'size_t' and \
                func.args[n + 1].name.endswith(u'len'):
            return f'%apply(char *STRING, size_t LENGTH) {{ ({arg.type} {arg.name}, size_t {func.args[n + 1].name}) }};'
        return u''

    swig = []
    for func in funcs:
        num_args = len(func.args)
        mapped = [map_arg(func, arg, i, num_args) for i, arg in enumerate(func.args)]
        swig.extend([m for m in mapped if m])

    swig = sorted(set(swig))
    replace_text(u'src/swig_java/swig.i', swig,
                 [u'/* BEGIN AUTOGENERATED */', u'/* END AUTOGENERATED */'])


def gen_wally_hpp(funcs):
    cpp, cpp_elements = {}, {}
    for func in funcs:
        num_args = len(func.args)
        vardecl = ''
        t_types, cpp_args, call_args = [], [], []
        skip = False
        for n, arg in enumerate(func.args):
            if skip:
                skip = False
                continue
            if is_buffer(func, arg, n, num_args) or is_int_buffer(func, arg, n, num_args):
                t_types.append(f'class {arg.name.upper()}')
                const = u'const ' if arg.is_const else ''
                cpp_args.append(f'{const}{arg.name.upper()}& {arg.name}')
                call_args.extend([f'{arg.name}.data()', f'{arg.name}.size()'])
                skip = True
            elif arg.type == u'size_t*' and arg.name == u'written' and \
                    n >= 2 and is_buffer(func, func.args[n-2], n-2, num_args):
                vardecl = u'    size_t n;'
                cpp_args.append(f'{arg.type} {arg.name} = 0')
                call_args.append(f'{arg.name} ? {arg.name} : &n')
            elif arg.type in [u'int', u'size_t', u'uint32_t', u'uint64_t',
                              u'int*', u'size_t*', u'uint32_t*', u'uint64_t*']:
                cpp_args.append(f'{arg.type} {arg.name}')
                call_args.append(f'{arg.name}')
            elif arg.is_pointer:
                if arg.is_pointer_pointer or n == num_args - 1:
                    cpp_args.append(f'{arg.type} {arg.name}')
                    call_args.append(f'{arg.name}')
                else:
                    t_types.append(f'class {arg.name.upper()}')
                    cpp_args.append(f'const {arg.name.upper()}& {arg.name}')
                    call_args.append(f'detail::get_p({arg.name})')

        impl = []
        if len(t_types):
            impl.append(f'template <{", ".join(t_types)}>')
        func_name = func.name[6:] if func.name.startswith(u'wally_') else func.name
        impl.append(f'inline int {func_name}({", ".join(cpp_args)}) {{')
        if vardecl:
            impl.append(vardecl)
        impl.append(f'    int ret = ::{func.name}({", ".join(call_args)});')
        if vardecl:
            prev = func.args[-3]
            impl.append(f'    return written || ret != WALLY_OK ? ret : n == static_cast<size_t>({prev.name}.size()) ? WALLY_OK : WALLY_EINVAL;')
        else:
            impl.append(f'    return ret;')
        impl.extend([u'}', u''])
        # FIXME: sort
        (cpp_elements if func.is_elements else cpp)[func.name] = impl

    text = []
    for f in sorted(cpp.keys()):
        text.extend(cpp[f])
    text.append(u'#ifdef BUILD_ELEMENTS')
    for f in sorted(cpp_elements.keys()):
        text.extend(cpp_elements[f])
    text[-1] = u'#endif // BUILD_ELEMENTS'
    replace_text(u'include/wally.hpp', text,
                 [u'/* BEGIN AUTOGENERATED */', u'/* END AUTOGENERATED */'])


def gen_wasm_exports(funcs):
    funcs = sorted(funcs)
    exports = ','.join([f"'_{func.name}' \\\n" for func in funcs if not func.is_elements])
    elements_exports = ','.join([f"'_{func.name}' \\\n" for func in funcs if func.is_elements])

    text = [
        f"EXPORTED_FUNCTIONS=\"['_malloc','_free',{exports}\"",
        'if [ -n "$ENABLE_ELEMENTS" ]; then',
        f'    EXPORTED_FUNCTIONS="$EXPORTED_FUNCTIONS"",{elements_exports}"',
        'fi',
        'EXPORTED_FUNCTIONS="$EXPORTED_FUNCTIONS""]"'
    ]
    replace_text(u'tools/wasm_exports.sh', text,
                 [u'# BEGIN AUTOGENERATED', u'# END AUTOGENERATED'])

def gen_wasm_package(funcs):

    # Simple single-argument types that can be identified without inspecting the next arguments
    typemap_simple = {
        # Simple primitive types
        'int'         : 'T.Int32',
        'size_t'      : 'T.Int32',
        'uint32_t'    : 'T.Int32',
        'uint64_t'    : 'T.Int64',

        'const char*' : 'T.String',

        # Single-argument pointers
        'size_t*'   : 'T.DestPtr(T.Int32)',
        'uint64_t*' : 'T.DestPtr(T.Int64)',
        'char**'    : 'T.DestPtrPtr(T.String)',

        # These are only used once
        'char*' : 'T.OpaqueRef', # as the argument to `wally_free_string`
        'void*' : 'T.OpaqueRef', # as the argument to `wally_bzero`
        'wally_map_verify_fn_t' : 'T.OpaqueRef', # as the argument to `wally_map_init`
    }

    # Arrays are represented as two arguments - the first identified by this map, followed by a FOO_len argument
    typemap_arrays = {
         'const unsigned char*' : 'T.Bytes',
         'const uint32_t*'      : 'T.Uint32Array',
         'const uint64_t*'      : 'T.Uint64Array',
    }

    # Expected sizes for fixed-size output buffers
    # TODO extract sizes for all arguments. currently only a few are set to prevent the tests from breaking.
    out_buffer_sizes = {
        'wally_tx_get_txid.bytes_out': 'C.WALLY_TXHASH_LEN',
        'wally_sha256.bytes_out': 'C.SHA256_LEN',
    }

    def map_args(func):
        num_args = len(func.args)
        next_index = 0
        js_args = []

        while next_index < num_args:
            arg = func.args[next_index]
            curr_index = next_index
            next_index = next_index + 1

            # Simple single-argument input/output types
            if arg.type in typemap_simple:
                js_args.append(typemap_simple[arg.type])
                continue

            # Input array types
            if is_array(func, arg, curr_index, num_args, typemap_arrays.keys()):
                js_args.append(typemap_arrays[arg.type])
                next_index = next_index + 1 # skip next 'FOO_len' argument
                continue

            # Input opaque reference
            if arg.is_struct and arg.is_pointer and not arg.is_pointer_pointer:
                # Sanity check to make sure we don't misidentify unrelated arguments
                assert arg.struct_name.startswith("wally_") or arg.struct_name == "ext_key" or arg.struct_name == "words"
                js_args.append('T.OpaqueRef')
                continue

            # Output pointer to a byte buffer
            if is_array(func, arg, curr_index, num_args, ['unsigned char*']):
                # Sanity check to make sure we don't misidentify unrelated arguments
                assert arg.name.endswith("_out") or arg.name == 'scalar'

                # Variable-length buffers have an additional pointer for the number of bytes written/expected
                # See https://wally.readthedocs.io/en/latest/conventions/#variable-length-output-buffers
                if curr_index < num_args - 2 and func.args[curr_index + 2].type == 'size_t*' and func.args[curr_index + 2].name == 'written':
                    init_size = 100 # TODO
                    js_args.append(f'T.DestPtrVarLen({init_size})')
                    next_index = next_index + 2 # skip next two arguments: 'FOO_len' and 'written'
                else:
                    arg_size = out_buffer_sizes.get(f"{func.name}.{arg.name}", 100) # TODO fail if missing once we have all sizes
                    js_args.append(f'T.DestPtrSized({arg_size})')
                    next_index = next_index + 1 # skip next 'FOO_len' argument

                continue

            # Output pointer to an opaque reference
            if arg.is_struct and arg.is_pointer and arg.is_pointer_pointer:
                # Sanity check to make sure we don't misidentify unrelated arguments
                assert arg.struct_name.startswith("wally_") or arg.struct_name == "ext_key" or arg.struct_name == "words"

                js_args.append('T.DestPtrPtr(T.OpaqueRef)')
                continue

            assert False, f'ERROR: Unknown argument type "{arg.type}"'

        return js_args

    func_names = set([ func.name for func in funcs ])

    def export_name(func_name):

        # Strip the '_alloc' suffix (this is typically what the user wants)
        if func_name.endswith("_alloc"):
            func_name = func_name[0:-6]
        # Add '_noalloc' suffix to the non-alloc variation (should be used rarely)
        elif f"{func_name}_alloc" in func_names:
            func_name = f"{func_name}_noalloc"

        # Strip 'wally_' prefix to keep things DRY (everything is already namespaced under the package)
        if func_name.startswith('wally_'):
            func_name = func_name[6:]

        return func_name

    jscode = [
        f"export const {export_name(func.name)} = wrap('{func.name}', [{', '.join(map_args(func))}]);"
        for func in funcs
    ]
    jscode.sort()

    # Inject generated functions into functions.js
    replace_text(u'src/wasm_package/functions.js', jscode,
                 [u'// BEGIN AUTOGENERATED', u'// END AUTOGENERATED'])


    # Update libwally constants in const.js
    os.system("cd src/wasm_package && npm run update-consts")


if __name__ == "__main__":

    non_elements = get_non_elements_functions()

    internal_only = len(sys.argv) > 1 and sys.argv[1] == '--internal'
     # Call sphinx to dump our definitions
    envs = {k:v for k,v in os.environ.items()}
    envs[u'WALLY_DOC_DUMP_FUNCS'] = u'1'
    if internal_only:
        envs[u'WALLY_DOC_DUMP_INTERNAL'] = u'1'
    cmd = ['sphinx-build', '-b', 'html', '-a', '-c', 'docs/source', 'docs/source', 'docs/build/html']
    process = subprocess.run(cmd, stdout=subprocess.PIPE, stderr=subprocess.DEVNULL, env=envs)

    # Process the lines into func objects for each function
    funcs = process.stdout.decode('utf-8').split(u'\n')
    funcs = [Func(f, non_elements) for f in funcs if f.startswith(u'int ')]

    # Generate the wrapper code
    gen_python_cffi(funcs, internal_only)
    if not internal_only:
        gen_python_swig(funcs)
        gen_java_swig(funcs)
        gen_wally_hpp(funcs)
        gen_wasm_exports(funcs)
        gen_wasm_package(funcs)
