if(ENABLE_DEBUG AND ENABLE_COVERAGE AND ${ENABLE_DEBUG} AND ${ENABLE_COVERAGE})
if(CMAKE_C_COMPILER_ID AND ("${CMAKE_C_COMPILER_ID}" MATCHES "(Apple)?[Cc]lang"))
message(STATUS "[libwally coverage] Clang not supported.")
set(PROFILE_ARCS_OPT "")
set(TEST_COVERAGE_OPT "")
set(GCOV_LIBRARY "")
# set(TEST_COVERAGE_OPT -fprofile-instr-generate)
# set(PROFILE_ARCS_OPT  -fcoverage-mapping)
# set(GCOV_LIBRARY gcov)
else()
set(COLLECT_COVERAGE ON)
set(COVERAGE 1)
set(PROFILE_ARCS_OPT -fprofile-arcs)
set(TEST_COVERAGE_OPT -ftest-coverage)
set(GCOV_LIBRARY gcov)
endif()
else()
set(PROFILE_ARCS_OPT  "")
set(TEST_COVERAGE_OPT "")
set(GCOV_LIBRARY  "")
endif()
